#:import C kivy.utils.get_color_from_hex
<Label>:
	font_name: 'Riona'
	markup: True
<FlyerLbl@Label>:
	font_size: 18
<FlyerBtn@Button>:
	font_name: 'Riona'
	font_size: 18
	background_normal: 'yellow_normal.png'
	background_down: 'yellow_down.png'
	bold: True
	border: (2,2,2,2)
	color: C('##0088D6')
<FlyerInput@TextInput>:
	font_name: 'Riona'
	font_size: 20
	background_active: 'blue.png'
	background_color: C('#0088D6')
	border: (2,2,2,2)
	cursor_color: C('#FDDE2E')
	padding: [5, ( self.height - self.line_height ) / 2] 
	multiline: False
	

BoxLayout:

	orientation: 'vertical'
	padding: 10
	spacing: 10

	FlyerLbl:
		text: '[color=#FDDE2E]Flyer[/color]'
		font_size: 60
		bold: True
		canvas:
			Color:
				rgba: C('#FDDE2E')
			Rectangle:
				size: self.size[0], self.size[1]*0.1
				pos: self.pos
		size_hint_y: 2


	FlyerLbl:
		text: 'Select User:'
		halign: 'left'
		valign: 'middle'
		size_hint_y: 0.5

	FlyerInput:
		id: userId
		color: C('#FDDE2E')
		size_hint_y: 0.5

	FlyerLbl:
		text: 'Enter Password:'
		size_hint_y: 0.5

	FlyerInput:
		id: password
		size_hint_y: 0.5

	FlyerBtn:
		text: 'Log In'
		size_hint_y: 1
		on_press: app.getUserDetails()


	
	         

