AddLocationForm:
<AddLocationForm>:
	orientation: "vertical"
	search_input: search_input
	BoxLayout:
		height: "40dp"
		size_hint_y: None
		TextInput:
			id: search_input
			size_hint_x: 50
		Button:
			text: "Search"
			on_press: root.search_location()
			size_hint_x: 25
		Button:
			text: "Current Location"
			size_hint_x: 25
	ListView:
		item_strings: ["JB", "EA", "VS", "ASHF", "Mantri", "Salarpuria", "BMC", "OMTP"]